#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 1 "..\..\Views\Nav\Menu.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    
    #line 2 "..\..\Views\Nav\Menu.cshtml"
    using System.Threading;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RecoWeb.Module;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Nav/Menu.cshtml")]
    public partial class _Views_Nav_Menu_cshtml : System.Web.Mvc.WebViewPage<RecoWeb.Module.Models.NavMenuInquiryViewModel>
    {
        public _Views_Nav_Menu_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<nav");

WriteLiteral(" class=\"navbar-default navbar-static-side\"");

WriteLiteral(" role=\"navigation\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"sidebar-collapse\"");

WriteLiteral(">\r\n        <ul");

WriteLiteral(" class=\"nav\"");

WriteLiteral(" id=\"side-menu\"");

WriteLiteral(">\r\n            <li");

WriteLiteral(" class=\"nav-header\"");

WriteLiteral(">\r\n                ");

WriteLiteral("\r\n                ");

WriteLiteral("\r\n\r\n                ");

WriteLiteral("\r\n\r\n                <div");

WriteLiteral(" class=\"dropdown profile-element\"");

WriteLiteral(">\r\n                    <span>\r\n                        ");

WriteLiteral("\r\n                    </span>\r\n                    <a");

WriteLiteral(" data-toggle=\"dropdown\"");

WriteLiteral(" class=\"dropdown-toggle\"");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"clear\"");

WriteLiteral(">\r\n                            ");

WriteLiteral("\r\n                            <span");

WriteLiteral(" class=\"text-muted text-xs block\"");

WriteLiteral(">");

            
            #line 36 "..\..\Views\Nav\Menu.cshtml"
                                                              Write(User.Identity.Name);

            
            #line default
            #line hidden
WriteLiteral("<b");

WriteLiteral(" class=\"caret\"");

WriteLiteral("></b></span>\r\n                        </span>\r\n                    </a>\r\n        " +
"            <ul");

WriteLiteral(" class=\"dropdown-menu dropdown-alerts animated fadeInRight m-t-xs\"");

WriteLiteral(">\r\n                        <li>\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(">\r\n                                <div>\r\n                                    <i");

WriteLiteral(" class=\"fa fa-key\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> 비밀번호 변경\r\n                                </div>\r\n                          " +
"  </a>\r\n                        </li>\r\n                        <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                        <li>\r\n                            <div");

WriteLiteral(" class=\"div-language\"");

WriteLiteral(" style=\"padding:3px 10px; min-height:0;\"");

WriteLiteral(">\r\n                                ");

WriteLiteral("\r\n\r\n");

            
            #line 53 "..\..\Views\Nav\Menu.cshtml"
                                
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Nav\Menu.cshtml"
                                  
                                    // 나라 이미지를 추가할때 필요한것
                                    // 1. ~/Content/Images/나라이름_32.png
                                    // 2. <a태그 안에 class="btn-language-transform language-나라이름"추가
                                    // * 1번과 2번의 나라이름은 동일하게 사용해야함.

                                    // 현재 이미지 클릭시 Redirect 했을때 클릭된 이미지로 (나라이름_clicked_32.png) 변경되도록 해야함.
                                    CultureInfo currentCulture = Thread.CurrentThread.CurrentCulture;

            
            #line default
            #line hidden
WriteLiteral("                                    <a");

WriteLiteral(" href=\"/Account/ChangeCurrentCulture/0\"");

WriteLiteral(" class=\"btn-language-transform language-south-korea\"");

WriteLiteral("><img");

WriteLiteral(" src=\"../Content/Images/south-korea_32.png\"");

WriteLiteral(" /></a>\r\n");

WriteLiteral("                                    <a");

WriteLiteral(" href=\"/Account/ChangeCurrentCulture/1\"");

WriteLiteral(" class=\"btn-language-transform language-usa\"");

WriteLiteral("><img");

WriteLiteral(" src=\"../Content/Images/usa_32.png\"");

WriteLiteral(" /></a>\r\n");

            
            #line 63 "..\..\Views\Nav\Menu.cshtml"
                                
            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n                        </li>\r\n            " +
"            <li");

WriteLiteral(" class=\"divider\"");

WriteLiteral("></li>\r\n                        <li>\r\n                            <a");

WriteAttribute("href", Tuple.Create(" href=\"", 3914), Tuple.Create("\"", 3953)
            
            #line 68 "..\..\Views\Nav\Menu.cshtml"
, Tuple.Create(Tuple.Create("", 3921), Tuple.Create<System.Object, System.Int32>(Url.Action("LogOff", "Account")
            
            #line default
            #line hidden
, 3921), false)
);

WriteLiteral(">\r\n                                <i");

WriteLiteral(" class=\"fa fa-sign-out\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral("></i> 로그아웃\r\n                            </a>\r\n                        </li>\r\n    " +
"                </ul>\r\n                </div>\r\n\r\n                ");

WriteLiteral("\r\n                ");

WriteLiteral("\r\n            </li>\r\n\r\n            ");

WriteLiteral("\r\n            <li");

WriteLiteral(" class=\"in \"");

WriteLiteral(">\r\n                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 4389), Tuple.Create("\"", 4423)
            
            #line 83 "..\..\Views\Nav\Menu.cshtml"
, Tuple.Create(Tuple.Create("", 4396), Tuple.Create<System.Object, System.Int32>(Url.Action("Index","Home")
            
            #line default
            #line hidden
, 4396), false)
);

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-home\"");

WriteLiteral("></i><span");

WriteLiteral(" class=\"nav-label\"");

WriteLiteral(">Home</span></a>\r\n            </li>\r\n\r\n\r\n\r\n         \r\n");

            
            #line 89 "..\..\Views\Nav\Menu.cshtml"
            
            
            #line default
            #line hidden
            
            #line 89 "..\..\Views\Nav\Menu.cshtml"
             foreach (var menu in Model.COW_NavMenuListInquiry.Where(s => s.ParentMenuCode == "Root"))
            {
                
            
            #line default
            #line hidden
            
            #line 130 "..\..\Views\Nav\Menu.cshtml"
                       
            }

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");

WriteLiteral("\r\n\r\n \r\n\r\n\r\n\r\n        </ul>\r\n    </div>\r\n</nav>");

        }
    }
}
#pragma warning restore 1591
