#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using RecoWeb.Module;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ExternalLoginConfirmation.cshtml")]
    public partial class _Views_Account_ExternalLoginConfirmation_cshtml : System.Web.Mvc.WebViewPage<RecoWeb.Module.Models.ExternalLoginConfirmationViewModel>
    {
        public _Views_Account_ExternalLoginConfirmation_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h3>Associate your ");

            
            #line 4 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
              Write(ViewBag.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral(" account.</h3>\r\n\r\n");

            
            #line 6 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
 using (Html.BeginForm("ExternalLoginConfirmation", "Account", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
{
    
            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 8 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                            


            
            #line default
            #line hidden
WriteLiteral("    <h4>Association Form</h4>\r\n");

WriteLiteral("    <hr />\r\n");

            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
    
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    <p");

WriteLiteral(" class=\"text-info\"");

WriteLiteral(">\r\n        You\'ve successfully authenticated with <strong>");

            
            #line 14 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
                                                  Write(ViewBag.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral("</strong>.\r\n            Please enter a user name for this site below and click th" +
"e Register button to finish\r\n            logging in.\r\n    </p>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
   Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 21 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
       Write(Html.TextBoxFor(m => m.UserName, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("            ");

            
            #line 22 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
       Write(Html.ValidationMessageFor(m => m.UserName));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Register\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

            
            #line 30 "..\..\Views\Account\ExternalLoginConfirmation.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("\r\n\r\n<script");

WriteLiteral(" src=\"../Scripts/jquery.validate.min.js\"");

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
