#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Account\Manage.cshtml"
    using Microsoft.AspNet.Identity;
    
    #line default
    #line hidden
    using RecoWeb.Module;
    
    #line 1 "..\..\Views\Account\Manage.cshtml"
    using RecoWeb.Module.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Manage.cshtml")]
    public partial class _Views_Account_Manage_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Account_Manage_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"wrapper wrapper-content animated fadeInRight\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-12\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"ibox float-e-margins\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"ibox-title\"");

WriteLiteral(">\r\n                    <h5><small>");

            
            #line 10 "..\..\Views\Account\Manage.cshtml"
                          Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</small></h5>\r\n                    <div");

WriteLiteral(" class=\"ibox-tools\"");

WriteLiteral(">\r\n                        <a");

WriteLiteral(" class=\"collapse-link\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-chevron-up\"");

WriteLiteral("></i>\r\n                        </a>\r\n                        <a");

WriteLiteral(" class=\"close-link\"");

WriteLiteral(">\r\n                            <i");

WriteLiteral(" class=\"fa fa-times\"");

WriteLiteral("></i>\r\n                        </a>\r\n                    </div>\r\n                " +
"</div>\r\n                <div");

WriteLiteral(" class=\"ibox-content\"");

WriteLiteral(">\r\n                    \r\n");

            
            #line 22 "..\..\Views\Account\Manage.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 22 "..\..\Views\Account\Manage.cshtml"
                     if (ViewBag.HasLocalPassword)
                    {
                        
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\Manage.cshtml"
                   Write(Html.Partial("_ChangePasswordPartial"));

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Account\Manage.cshtml"
                                                               
                    }
                    else
                    {
                        
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Account\Manage.cshtml"
                   Write(Html.Partial("_SetPasswordPartial"));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Account\Manage.cshtml"
                                                            
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <section");

WriteLiteral(" id=\"externalLogins\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 32 "..\..\Views\Account\Manage.cshtml"
                   Write(Html.Action("RemoveAccountList"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 33 "..\..\Views\Account\Manage.cshtml"
                   Write(Html.Partial("_ExternalLoginsListPartial", new { Action = "LinkLogin", ReturnUrl = ViewBag.ReturnUrl }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </section>\r\n                </div>\r\n            </div>\r\n   " +
"     </div>\r\n    </div>\r\n</div>\r\n\r\n");

WriteLiteral("\r\n\r\n<script");

WriteLiteral(" src=\"../Scripts/jquery.validate.min.js\"");

WriteLiteral("></script>");

        }
    }
}
#pragma warning restore 1591
