#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/Register.cshtml")]
    public partial class _Views_Account_Register_cshtml : System.Web.Mvc.WebViewPage<RecoWeb.Module.Models.RegisterViewModel>
    {
        public _Views_Account_Register_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\Register.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n\r\n    <title>INSPINIA | Login</title>\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 268), Tuple.Create("\"", 302)
, Tuple.Create(Tuple.Create("", 275), Tuple.Create<System.Object, System.Int32>(Href("~/Content/bootstrap.min.css")
, 275), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 332), Tuple.Create("\"", 380)
, Tuple.Create(Tuple.Create("", 339), Tuple.Create<System.Object, System.Int32>(Href("~/Fonts/font-awesome/css/font-awesome.css")
, 339), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 412), Tuple.Create("\"", 440)
, Tuple.Create(Tuple.Create("", 419), Tuple.Create<System.Object, System.Int32>(Href("~/Content/animate.css")
, 419), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 470), Tuple.Create("\"", 496)
, Tuple.Create(Tuple.Create("", 477), Tuple.Create<System.Object, System.Int32>(Href("~/Content/style.css")
, 477), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(">\r\n\r\n</head>\r\n\r\n<body");

WriteLiteral(" class=\"gray-bg\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" class=\"middle-box text-center loginscreen  animated fadeInDown\"");

WriteLiteral(">\r\n        <div>\r\n");

            
            #line 28 "..\..\Views\Account\Register.cshtml"
            
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Account\Register.cshtml"
             using (Html.BeginForm("Register", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
                
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Account\Register.cshtml"
           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Account\Register.cshtml"
                                        

            
            #line default
            #line hidden
WriteLiteral("                <h4>Create a new account.</h4>\r\n");

WriteLiteral("                <hr />\r\n");

            
            #line 33 "..\..\Views\Account\Register.cshtml"
                
            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Account\Register.cshtml"
           Write(Html.ValidationSummary());

            
            #line default
            #line hidden
            
            #line 33 "..\..\Views\Account\Register.cshtml"
                                         

            
            #line default
            #line hidden
WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 35 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.UserName, new { @class = "col-md-5 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 37 "..\..\Views\Account\Register.cshtml"
                   Write(Html.TextBoxFor(m => m.UserName, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.Password, new { @class = "col-md-5 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Views\Account\Register.cshtml"
                   Write(Html.PasswordFor(m => m.Password, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 47 "..\..\Views\Account\Register.cshtml"
               Write(Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-5 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-7\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 49 "..\..\Views\Account\Register.cshtml"
                   Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n");

WriteLiteral("                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-8\"");

WriteLiteral(">\r\n                        <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" value=\"Register\"");

WriteLiteral(" />\r\n                    </div>\r\n                </div>\r\n");

            
            #line 57 "..\..\Views\Account\Register.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n\r\n");

WriteLiteral("\r\n\r\n<script");

WriteLiteral(" src=\"../Scripts/jquery.validate.min.js\"");

WriteLiteral("></script>\r\n");

        }
    }
}
#pragma warning restore 1591
