#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using DevExtreme.AspNet.Mvc;
    
    #line 2 "..\..\Views\System\Permissions.cshtml"
    using RecoWeb.Domain.LocalResource;
    
    #line default
    #line hidden
    using RecoWeb.Module;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/System/Permissions.cshtml")]
    public partial class _Views_System_Permissions_cshtml : System.Web.Mvc.WebViewPage<RecoWeb.Module.Models.PermissionViewModel>
    {
        public _Views_System_Permissions_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 4 "..\..\Views\System\Permissions.cshtml"
  

    AjaxOptions ajaxInquiry = new AjaxOptions
    {
        HttpMethod = "GET",
        InsertionMode = InsertionMode.Replace,
        OnSuccess = "ContextInquiry",
        UpdateTargetId = "Context"

    };

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 15 "..\..\Views\System\Permissions.cshtml"
 using (Ajax.BeginForm("AjaxInquiryContextMenuPermissions", "System", ajaxInquiry))
{

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"row wrapper border-bottom white-bg page-heading\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-lg-8 col-md-8 col-xs-12\"");

WriteLiteral(" style=\"display:flex;\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" style=\"font-size:3rem; float:left; margin-right:0.5rem;\"");

WriteLiteral(">");

            
            #line 19 "..\..\Views\System\Permissions.cshtml"
                                                                      Write(Model.resourceManager.String("Menu_" + Model.ActivePage));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <div");

WriteLiteral(" style=\"align-self:flex-end; padding:0.5rem\"");

WriteLiteral(">\r\n                <ol");

WriteLiteral(" class=\"breadcrumb\"");

WriteLiteral(">\r\n                    <li>\r\n                        <a");

WriteAttribute("href", Tuple.Create(" href=\"", 839), Tuple.Create("\"", 874)
            
            #line 23 "..\..\Views\System\Permissions.cshtml"
, Tuple.Create(Tuple.Create("", 846), Tuple.Create<System.Object, System.Int32>(Url.Action("Index", "Home")
            
            #line default
            #line hidden
, 846), false)
);

WriteLiteral(">");

            
            #line 23 "..\..\Views\System\Permissions.cshtml"
                                                          Write(Resource.Menu_Home);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                    </li>\r\n\r\n");

            
            #line 26 "..\..\Views\System\Permissions.cshtml"
                    
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\System\Permissions.cshtml"
                     foreach (var page in Model.MenuLocation)
                    {
                        if (page == Model.ActivePage)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(">\r\n                                <strong>");

            
            #line 31 "..\..\Views\System\Permissions.cshtml"
                                   Write(Model.resourceManager.String("Menu_" + @page));

            
            #line default
            #line hidden
WriteLiteral(" </strong>\r\n                            </li>\r\n");

            
            #line 33 "..\..\Views\System\Permissions.cshtml"
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <li>\r\n                                <span>");

            
            #line 37 "..\..\Views\System\Permissions.cshtml"
                                 Write(Model.resourceManager.String("Menu_" + @page));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </li>\r\n");

            
            #line 39 "..\..\Views\System\Permissions.cshtml"
                        }
                    }

            
            #line default
            #line hidden
WriteLiteral("                </ol>\r\n            </div>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"col-lg-4 col-md-4\"");

WriteLiteral(" style=\"margin-top: 0.5rem;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn-group pull-right \"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" id=\"btn-find\"");

WriteLiteral("><i");

WriteLiteral(" class=\"fa fa-check\"");

WriteLiteral("></i>&nbsp;");

            
            #line 46 "..\..\Views\System\Permissions.cshtml"
                                                                                                        Write(Resource.Inquiry);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"row wrapper border-bottom white-bg check-item\"");

WriteLiteral(">\r\n    </div>\r\n");

            
            #line 52 "..\..\Views\System\Permissions.cshtml"

}

            
            #line default
            #line hidden
WriteLiteral("<div");

WriteLiteral(" id=\"Context\"");

WriteLiteral(" class=\"row wrapper wrapper-content animated fadeInRight\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 55 "..\..\Views\System\Permissions.cshtml"
Write(Html.Partial("_Permissions"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"modal inmodal fade\"");

WriteLiteral(" id=\"Modals\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" onload=\"Loads()\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 60 "..\..\Views\System\Permissions.cshtml"
   Write(Html.Partial("_PopupPermissionsAddRole", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n<div");

WriteLiteral(" class=\"modal inmodal fade\"");

WriteLiteral(" id=\"ModalsEmployee\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"modal-dialog modal-lg\"");

WriteLiteral(" onload=\"Loads()\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 66 "..\..\Views\System\Permissions.cshtml"
   Write(Html.Partial("_PopupPermissionsAddEmployee", Model));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n\r\n");

DefineSection("Styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 2646), Tuple.Create("\"", 2707)
            
            #line 72 "..\..\Views\System\Permissions.cshtml"
, Tuple.Create(Tuple.Create("", 2653), Tuple.Create<System.Object, System.Int32>(Url.Action("plugins/jqGrid/ui.jqgrid.css", "Content")
            
            #line default
            #line hidden
, 2653), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" type=\"text/css\"");

WriteLiteral(" />\r\n");

});

WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"../Scripts/jquery-3.1.1.min.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"../Scripts/plugins/jqGrid/i18n/grid.locale-en.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"../Scripts/plugins/jqGrid/jquery.jqGrid.min.js\"");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral("></script>\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n\r\n        function ContextInquiry(returnValue) {\r\n            var data = retur" +
"nValue;\r\n        }\r\n        var treeSelectedRow;\r\n        var isFisrt = true;\r\n " +
"       function tree1Change(selectedRow) {\r\n            try {\r\n                t" +
"reeSelectedRow = selectedRow;\r\n                var orders = new DevExpress.data." +
"CustomStore({\r\n                    load: function (loadOptions) {\r\n             " +
"           var deferred = $.Deferred(),\r\n                            args = {};\r" +
"\n\r\n                        if (loadOptions.sort) {\r\n                            " +
"args.orderby = loadOptions.sort[0].selector;\r\n                            if (lo" +
"adOptions.sort[0].desc)\r\n                                args.orderby += \" desc\"" +
";\r\n                        }\r\n\r\n                        $.ajax({\r\n              " +
"              url: \"../System/GetCOW_PermissionRoleInquiry?menuCode=\" + treeSele" +
"ctedRow.selectedRowsData[0].MenuCode,\r\n                            dataType: \"js" +
"on\",\r\n                            data: args,\r\n                            succe" +
"ss: function (result) {\r\n                                deferred.resolve(result" +
".data);\r\n                            },\r\n                            error: func" +
"tion (e) {\r\n                                console.log(\"오류발생\");\r\n              " +
"                  console.log(e);\r\n                                deferred.reje" +
"ct(\"Data Loading Error\");\r\n                            },\r\n                     " +
"       timeout: 10000\r\n                        });\r\n                        retu" +
"rn deferred.promise();\r\n                    }\r\n                });\r\n            " +
"    $(\"#gridContainer02\").dxDataGrid({\r\n                    dataSource: {\r\n     " +
"                   store: orders\r\n                    }\r\n                }).dxDa" +
"taGrid(\"instance\").refresh();\r\n\r\n                var orders2 = new DevExpress.da" +
"ta.CustomStore({\r\n                    load: function (loadOptions) {\r\n          " +
"              var deferred = $.Deferred(),\r\n                            args = {" +
"};\r\n\r\n                        if (loadOptions.sort) {\r\n                         " +
"   args.orderby = loadOptions.sort[0].selector;\r\n                            if " +
"(loadOptions.sort[0].desc)\r\n                                args.orderby += \" de" +
"sc\";\r\n                        }\r\n\r\n                        $.ajax({\r\n           " +
"                 url: \"../System/GetCOW_PermissionEmployeeInquiry?menuCode=\" + t" +
"reeSelectedRow.selectedRowsData[0].MenuCode,\r\n                            dataTy" +
"pe: \"json\",\r\n                            data: args,\r\n                          " +
"  success: function (result) {\r\n                                deferred.resolve" +
"(result.data);\r\n                            },\r\n                            erro" +
"r: function (e) {\r\n                                console.log(\"오류발생\");\r\n       " +
"                         console.log(e);\r\n                                deferr" +
"ed.reject(\"Data Loading Error\");\r\n                            },\r\n              " +
"              timeout: 10000\r\n                        });\r\n                     " +
"   return deferred.promise();\r\n                    }\r\n                });\r\n     " +
"           $(\"#gridContainer03\").dxDataGrid({\r\n                    dataSource: {" +
"\r\n                        store: orders2\r\n                    }\r\n               " +
" }).dxDataGrid(\"instance\").refresh();\r\n\r\n            } catch (e) {\r\n            " +
"    console.log(e);\r\n            }\r\n        }\r\n\r\n        $(document).ready(funct" +
"ion () {\r\n\r\n            $(\':input:checked\').parent(\'.btn\').addClass(\'active\');\r\n" +
"\r\n            //권한 추가 클릭\r\n            $(\'#btnCreateRole\').click(function () {\r\n " +
"               try\r\n                {\r\n                    if (treeSelectedRow) " +
"{\r\n                        var pids = $(\'#gridContainer02\').dxDataGrid(\'instance" +
"\').getSelectedRowsData();\r\n                        if (pids.length > 0) {\r\n     " +
"                       if (SetCOW_PermissionRoleCreateSave(treeSelectedRow.selec" +
"tedRowsData[0].MenuCode, pids)) {\r\n                                var orders = " +
"new DevExpress.data.CustomStore({\r\n                                    load: fun" +
"ction (loadOptions) {\r\n                                        var deferred = $." +
"Deferred(),\r\n                                            args = {};\r\n\r\n         " +
"                               if (loadOptions.sort) {\r\n                        " +
"                    args.orderby = loadOptions.sort[0].selector;\r\n              " +
"                              if (loadOptions.sort[0].desc)\r\n                   " +
"                             args.orderby += \" desc\";\r\n                         " +
"               }\r\n\r\n                                        $.ajax({\r\n          " +
"                                  url: \"../System/GetCOW_PermissionRoleInquiry?m" +
"enuCode=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                     " +
"                       dataType: \"json\",\r\n                                      " +
"      data: args,\r\n                                            success: function" +
" (result) {\r\n                                                deferred.resolve(re" +
"sult.data);\r\n                                            },\r\n                   " +
"                         error: function (e) {\r\n                                " +
"                console.log(\"오류발생\");\r\n                                          " +
"      console.log(e);\r\n                                                deferred." +
"reject(\"Data Loading Error\");\r\n                                            },\r\n " +
"                                           timeout: 10000\r\n                     " +
"                   });\r\n                                        return deferred." +
"promise();\r\n                                    }\r\n                             " +
"   });\r\n                                $(\"#gridContainer02\").dxDataGrid({\r\n    " +
"                                dataSource: {\r\n                                 " +
"       store: orders\r\n                                    }\r\n                   " +
"             }).dxDataGrid(\"instance\").refresh();\r\n                            }" +
"\r\n                        }\r\n                    }\r\n                } catch (e) " +
"{\r\n                    console.log(e);\r\n                }\r\n            });\r\n\r\n  " +
"          //권한 읽기 클릭\r\n            $(\'#btnReadRole\').click(function () {\r\n       " +
"         try {\r\n                    if (treeSelectedRow) {\r\n                    " +
"    var pids = $(\'#gridContainer02\').dxDataGrid(\'instance\').getSelectedRowsData(" +
");\r\n                        if (pids.length > 0) {\r\n                            " +
"if (SetCOW_PermissionRoleReadSave(treeSelectedRow.selectedRowsData[0].MenuCode, " +
"pids)) {\r\n                                var orders = new DevExpress.data.Custo" +
"mStore({\r\n                                    load: function (loadOptions) {\r\n  " +
"                                      var deferred = $.Deferred(),\r\n            " +
"                                args = {};\r\n\r\n                                  " +
"      if (loadOptions.sort) {\r\n                                            args." +
"orderby = loadOptions.sort[0].selector;\r\n                                       " +
"     if (loadOptions.sort[0].desc)\r\n                                            " +
"    args.orderby += \" desc\";\r\n                                        }\r\n\r\n     " +
"                                   $.ajax({\r\n                                   " +
"         url: \"../System/GetCOW_PermissionRoleInquiry?menuCode=\" + treeSelectedR" +
"ow.selectedRowsData[0].MenuCode,\r\n                                            da" +
"taType: \"json\",\r\n                                            data: args,\r\n      " +
"                                      success: function (result) {\r\n            " +
"                                    deferred.resolve(result.data);\r\n            " +
"                                },\r\n                                            " +
"error: function (e) {\r\n                                                console.l" +
"og(\"오류발생\");\r\n                                                console.log(e);\r\n  " +
"                                              deferred.reject(\"Data Loading Erro" +
"r\");\r\n                                            },\r\n                          " +
"                  timeout: 10000\r\n                                        });\r\n " +
"                                       return deferred.promise();\r\n             " +
"                       }\r\n                                });\r\n                 " +
"               $(\"#gridContainer02\").dxDataGrid({\r\n                             " +
"       dataSource: {\r\n                                        store: orders\r\n   " +
"                                 }\r\n                                }).dxDataGri" +
"d(\"instance\").refresh();\r\n                            }\r\n                       " +
" }\r\n                    }\r\n                } catch (e) {\r\n                    co" +
"nsole.log(e);\r\n                }\r\n            });\r\n\r\n            //권한 수정 클릭\r\n   " +
"         $(\'#btnUpdateRole\').click(function () {\r\n                try {\r\n       " +
"             if (treeSelectedRow) {\r\n                        var pids = $(\'#grid" +
"Container02\').dxDataGrid(\'instance\').getSelectedRowsData();\r\n                   " +
"     if (pids.length > 0) {\r\n                            if (SetCOW_PermissionRo" +
"leUpdateSave(treeSelectedRow.selectedRowsData[0].MenuCode, pids)) {\r\n           " +
"                     var orders = new DevExpress.data.CustomStore({\r\n           " +
"                         load: function (loadOptions) {\r\n                       " +
"                 var deferred = $.Deferred(),\r\n                                 " +
"           args = {};\r\n\r\n                                        if (loadOptions" +
".sort) {\r\n                                            args.orderby = loadOptions" +
".sort[0].selector;\r\n                                            if (loadOptions." +
"sort[0].desc)\r\n                                                args.orderby += \"" +
" desc\";\r\n                                        }\r\n\r\n                          " +
"              $.ajax({\r\n                                            url: \"../Sys" +
"tem/GetCOW_PermissionRoleInquiry?menuCode=\" + treeSelectedRow.selectedRowsData[0" +
"].MenuCode,\r\n                                            dataType: \"json\",\r\n    " +
"                                        data: args,\r\n                           " +
"                 success: function (result) {\r\n                                 " +
"               deferred.resolve(result.data);\r\n                                 " +
"           },\r\n                                            error: function (e) {" +
"\r\n                                                console.log(\"오류발생\");\r\n        " +
"                                        console.log(e);\r\n                       " +
"                         deferred.reject(\"Data Loading Error\");\r\n               " +
"                             },\r\n                                            tim" +
"eout: 10000\r\n                                        });\r\n                      " +
"                  return deferred.promise();\r\n                                  " +
"  }\r\n                                });\r\n                                $(\"#gr" +
"idContainer02\").dxDataGrid({\r\n                                    dataSource: {\r" +
"\n                                        store: orders\r\n                        " +
"            }\r\n                                }).dxDataGrid(\"instance\").refresh" +
"();\r\n                            }\r\n                        }\r\n                 " +
"   }\r\n                } catch (e) {\r\n                    console.log(e);\r\n      " +
"          }\r\n            });\r\n\r\n            //권한 삭제 클릭\r\n            $(\'#btnDelet" +
"eRole\').click(function () {\r\n                try {\r\n                    if (tree" +
"SelectedRow) {\r\n                        var pids = $(\'#gridContainer02\').dxDataG" +
"rid(\'instance\').getSelectedRowsData();\r\n                        if (pids.length " +
"> 0) {\r\n                            if (SetCOW_PermissionRoleDeleteSave(treeSele" +
"ctedRow.selectedRowsData[0].MenuCode, pids)) {\r\n                                " +
"var orders = new DevExpress.data.CustomStore({\r\n                                " +
"    load: function (loadOptions) {\r\n                                        var " +
"deferred = $.Deferred(),\r\n                                            args = {};" +
"\r\n\r\n                                        if (loadOptions.sort) {\r\n           " +
"                                 args.orderby = loadOptions.sort[0].selector;\r\n " +
"                                           if (loadOptions.sort[0].desc)\r\n      " +
"                                          args.orderby += \" desc\";\r\n            " +
"                            }\r\n\r\n                                        $.ajax(" +
"{\r\n                                            url: \"../System/GetCOW_Permission" +
"RoleInquiry?menuCode=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n        " +
"                                    dataType: \"json\",\r\n                         " +
"                   data: args,\r\n                                            succ" +
"ess: function (result) {\r\n                                                deferr" +
"ed.resolve(result.data);\r\n                                            },\r\n      " +
"                                      error: function (e) {\r\n                   " +
"                             console.log(\"오류발생\");\r\n                             " +
"                   console.log(e);\r\n                                            " +
"    deferred.reject(\"Data Loading Error\");\r\n                                    " +
"        },\r\n                                            timeout: 10000\r\n        " +
"                                });\r\n                                        ret" +
"urn deferred.promise();\r\n                                    }\r\n                " +
"                });\r\n                                $(\"#gridContainer02\").dxDat" +
"aGrid({\r\n                                    dataSource: {\r\n                    " +
"                    store: orders\r\n                                    }\r\n      " +
"                          }).dxDataGrid(\"instance\").refresh();\r\n                " +
"            }\r\n                        }\r\n                    }\r\n               " +
" } catch (e) {\r\n                    console.log(e);\r\n                }\r\n        " +
"    });\r\n\r\n            //역할없음 클릭\r\n            $(\'#btnNoAuthRole\').click(function" +
" () {\r\n\r\n                try {\r\n                    if (treeSelectedRow) {\r\n    " +
"                    var pids = $(\'#gridContainer02\').dxDataGrid(\'instance\').getS" +
"electedRowsData();\r\n                        if (pids.length > 0) {\r\n            " +
"                if (SetCOW_PermissionRoleNoAuthSave(treeSelectedRow.selectedRows" +
"Data[0].MenuCode, pids)) {\r\n                                var orders = new Dev" +
"Express.data.CustomStore({\r\n                                    load: function (" +
"loadOptions) {\r\n                                        var deferred = $.Deferre" +
"d(),\r\n                                            args = {};\r\n\r\n                " +
"                        if (loadOptions.sort) {\r\n                               " +
"             args.orderby = loadOptions.sort[0].selector;\r\n                     " +
"                       if (loadOptions.sort[0].desc)\r\n                          " +
"                      args.orderby += \" desc\";\r\n                                " +
"        }\r\n\r\n                                        $.ajax({\r\n                 " +
"                           url: \"../System/GetCOW_PermissionRoleInquiry?menuCode" +
"=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                            " +
"                dataType: \"json\",\r\n                                            d" +
"ata: args,\r\n                                            success: function (resul" +
"t) {\r\n                                                deferred.resolve(result.da" +
"ta);\r\n                                            },\r\n                          " +
"                  error: function (e) {\r\n                                       " +
"         console.log(\"오류발생\");\r\n                                                c" +
"onsole.log(e);\r\n                                                deferred.reject(" +
"\"Data Loading Error\");\r\n                                            },\r\n        " +
"                                    timeout: 10000\r\n                            " +
"            });\r\n                                        return deferred.promise" +
"();\r\n                                    }\r\n                                });\r" +
"\n                                $(\"#gridContainer02\").dxDataGrid({\r\n           " +
"                         dataSource: {\r\n                                        " +
"store: orders\r\n                                    }\r\n                          " +
"      }).dxDataGrid(\"instance\").refresh();\r\n                            }\r\n     " +
"                   }\r\n                    }\r\n                } catch (e) {\r\n    " +
"                console.log(e);\r\n                }\r\n            });\r\n\r\n         " +
"   //역할추가 버튼 클릭\r\n            $(\'#btnAddRole\').click(function () {\r\n             " +
"   if (treeSelectedRow) {\r\n                    var vv = $(\'#gridContainer02\').dx" +
"DataGrid(\'instance\').getDataSource();\r\n                    Popup_PermissionRoleA" +
"dd(treeSelectedRow.selectedRowsData[0].MenuCode, vv.items());\r\n                }" +
"\r\n            });\r\n\r\n            //역할삭제버튼 클릭\r\n            $(\'#btnRemoveRole\').cl" +
"ick(function () {\r\n\r\n                try {\r\n                    if (treeSelected" +
"Row) {\r\n                        var pids = $(\'#gridContainer02\').dxDataGrid(\'ins" +
"tance\').getSelectedRowsData();\r\n                        if (pids.length > 0) {\r\n" +
"                            if (SetCOW_PermissionRoleRemoveSave(treeSelectedRow." +
"selectedRowsData[0].MenuCode, pids)) {\r\n                                var orde" +
"rs = new DevExpress.data.CustomStore({\r\n                                    load" +
": function (loadOptions) {\r\n                                        var deferred" +
" = $.Deferred(),\r\n                                            args = {};\r\n\r\n    " +
"                                    if (loadOptions.sort) {\r\n                   " +
"                         args.orderby = loadOptions.sort[0].selector;\r\n         " +
"                                   if (loadOptions.sort[0].desc)\r\n              " +
"                                  args.orderby += \" desc\";\r\n                    " +
"                    }\r\n\r\n                                        $.ajax({\r\n     " +
"                                       url: \"../System/GetCOW_PermissionRoleInqu" +
"iry?menuCode=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                " +
"                            dataType: \"json\",\r\n                                 " +
"           data: args,\r\n                                            success: fun" +
"ction (result) {\r\n                                                deferred.resol" +
"ve(result.data);\r\n                                            },\r\n              " +
"                              error: function (e) {\r\n                           " +
"                     console.log(\"오류발생\");\r\n                                     " +
"           console.log(e);\r\n                                                defe" +
"rred.reject(\"Data Loading Error\");\r\n                                            " +
"},\r\n                                            timeout: 10000\r\n                " +
"                        });\r\n                                        return defe" +
"rred.promise();\r\n                                    }\r\n                        " +
"        });\r\n                                $(\"#gridContainer02\").dxDataGrid({\r" +
"\n                                    dataSource: {\r\n                            " +
"            store: orders\r\n                                    }\r\n              " +
"                  }).dxDataGrid(\"instance\").refresh();\r\n                        " +
"    }\r\n                        }\r\n                    }\r\n                } catch" +
" (e) {\r\n                    console.log(e);\r\n                }\r\n            });\r" +
"\n\r\n            //작업자 읽기 버튼 클릭\r\n            $(\'#btnCreateEmployee\').click(functio" +
"n () {\r\n                try {\r\n                    if (treeSelectedRow) {\r\n     " +
"                   var pids = $(\'#gridContainer03\').dxDataGrid(\'instance\').getSe" +
"lectedRowsData();\r\n                        if (pids.length > 0) {\r\n             " +
"               if (SetCOW_PermissionEmployeeCreateSave(treeSelectedRow.selectedR" +
"owsData[0].MenuCode, pids)) {\r\n                                var orders = new " +
"DevExpress.data.CustomStore({\r\n                                    load: functio" +
"n (loadOptions) {\r\n                                        var deferred = $.Defe" +
"rred(),\r\n                                            args = {};\r\n\r\n             " +
"                           if (loadOptions.sort) {\r\n                            " +
"                args.orderby = loadOptions.sort[0].selector;\r\n                  " +
"                          if (loadOptions.sort[0].desc)\r\n                       " +
"                         args.orderby += \" desc\";\r\n                             " +
"           }\r\n\r\n                                        $.ajax({\r\n              " +
"                              url: \"../System/GetCOW_PermissionEmployeeInquiry?m" +
"enuCode=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                     " +
"                       dataType: \"json\",\r\n                                      " +
"      data: args,\r\n                                            success: function" +
" (result) {\r\n                                                deferred.resolve(re" +
"sult.data);\r\n                                            },\r\n                   " +
"                         error: function (e) {\r\n                                " +
"                console.log(\"오류발생\");\r\n                                          " +
"      console.log(e);\r\n                                                deferred." +
"reject(\"Data Loading Error\");\r\n                                            },\r\n " +
"                                           timeout: 10000\r\n                     " +
"                   });\r\n                                        return deferred." +
"promise();\r\n                                    }\r\n                             " +
"   });\r\n                                $(\"#gridContainer03\").dxDataGrid({\r\n    " +
"                                dataSource: {\r\n                                 " +
"       store: orders\r\n                                    }\r\n                   " +
"             }).dxDataGrid(\"instance\").refresh();\r\n                            }" +
"\r\n                        }\r\n                    }\r\n                } catch (e) " +
"{\r\n                    console.log(e);\r\n                }\r\n            });\r\n\r\n  " +
"          //작업자 읽기 버튼 클릭\r\n            $(\'#btnReadEmployee\').click(function () {\r" +
"\n                try {\r\n                    if (treeSelectedRow) {\r\n            " +
"            var pids = $(\'#gridContainer03\').dxDataGrid(\'instance\').getSelectedR" +
"owsData();\r\n                        if (pids.length > 0) {\r\n                    " +
"        if (SetCOW_PermissionEmployeeReadSave(treeSelectedRow.selectedRowsData[0" +
"].MenuCode, pids)) {\r\n                                var orders = new DevExpres" +
"s.data.CustomStore({\r\n                                    load: function (loadOp" +
"tions) {\r\n                                        var deferred = $.Deferred(),\r\n" +
"                                            args = {};\r\n\r\n                      " +
"                  if (loadOptions.sort) {\r\n                                     " +
"       args.orderby = loadOptions.sort[0].selector;\r\n                           " +
"                 if (loadOptions.sort[0].desc)\r\n                                " +
"                args.orderby += \" desc\";\r\n                                      " +
"  }\r\n\r\n                                        $.ajax({\r\n                       " +
"                     url: \"../System/GetCOW_PermissionEmployeeInquiry?menuCode=\"" +
" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                              " +
"              dataType: \"json\",\r\n                                            dat" +
"a: args,\r\n                                            success: function (result)" +
" {\r\n                                                deferred.resolve(result.data" +
");\r\n                                            },\r\n                            " +
"                error: function (e) {\r\n                                         " +
"       console.log(\"오류발생\");\r\n                                                con" +
"sole.log(e);\r\n                                                deferred.reject(\"D" +
"ata Loading Error\");\r\n                                            },\r\n          " +
"                                  timeout: 10000\r\n                              " +
"          });\r\n                                        return deferred.promise()" +
";\r\n                                    }\r\n                                });\r\n " +
"                               $(\"#gridContainer03\").dxDataGrid({\r\n             " +
"                       dataSource: {\r\n                                        st" +
"ore: orders\r\n                                    }\r\n                            " +
"    }).dxDataGrid(\"instance\").refresh();\r\n                            }\r\n       " +
"                 }\r\n                    }\r\n                } catch (e) {\r\n      " +
"              console.log(e);\r\n                }\r\n            });\r\n\r\n           " +
" //작업자 수정 버튼 클릭\r\n            $(\'#btnUpdateEmployee\').click(function () {\r\n\r\n    " +
"            try {\r\n                    if (treeSelectedRow) {\r\n                 " +
"       var pids = $(\'#gridContainer03\').dxDataGrid(\'instance\').getSelectedRowsDa" +
"ta();\r\n                        if (pids.length > 0) {\r\n                         " +
"   if (SetCOW_PermissionEmployeeUpdateSave(treeSelectedRow.selectedRowsData[0].M" +
"enuCode, pids)) {\r\n                                var orders = new DevExpress.d" +
"ata.CustomStore({\r\n                                    load: function (loadOptio" +
"ns) {\r\n                                        var deferred = $.Deferred(),\r\n   " +
"                                         args = {};\r\n\r\n                         " +
"               if (loadOptions.sort) {\r\n                                        " +
"    args.orderby = loadOptions.sort[0].selector;\r\n                              " +
"              if (loadOptions.sort[0].desc)\r\n                                   " +
"             args.orderby += \" desc\";\r\n                                        }" +
"\r\n\r\n                                        $.ajax({\r\n                          " +
"                  url: \"../System/GetCOW_PermissionEmployeeInquiry?menuCode=\" + " +
"treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                                 " +
"           dataType: \"json\",\r\n                                            data: " +
"args,\r\n                                            success: function (result) {\r" +
"\n                                                deferred.resolve(result.data);\r" +
"\n                                            },\r\n                               " +
"             error: function (e) {\r\n                                            " +
"    console.log(\"오류발생\");\r\n                                                consol" +
"e.log(e);\r\n                                                deferred.reject(\"Data" +
" Loading Error\");\r\n                                            },\r\n             " +
"                               timeout: 10000\r\n                                 " +
"       });\r\n                                        return deferred.promise();\r\n" +
"                                    }\r\n                                });\r\n    " +
"                            $(\"#gridContainer03\").dxDataGrid({\r\n                " +
"                    dataSource: {\r\n                                        store" +
": orders\r\n                                    }\r\n                               " +
" }).dxDataGrid(\"instance\").refresh();\r\n                            }\r\n          " +
"              }\r\n                    }\r\n                } catch (e) {\r\n         " +
"           console.log(e);\r\n                }\r\n            });\r\n\r\n            //" +
"작업자 삭제 버튼 클릭\r\n            $(\'#btnDeleteEmployee\').click(function () {\r\n\r\n       " +
"         try {\r\n                    if (treeSelectedRow) {\r\n                    " +
"    var pids = $(\'#gridContainer03\').dxDataGrid(\'instance\').getSelectedRowsData(" +
");\r\n                        if (pids.length > 0) {\r\n\r\n                          " +
"  if (SetCOW_PermissionEmployeeDeleteSave(treeSelectedRow.selectedRowsData[0].Me" +
"nuCode, pids)) {\r\n                                var orders = new DevExpress.da" +
"ta.CustomStore({\r\n                                    load: function (loadOption" +
"s) {\r\n                                        var deferred = $.Deferred(),\r\n    " +
"                                        args = {};\r\n\r\n                          " +
"              if (loadOptions.sort) {\r\n                                         " +
"   args.orderby = loadOptions.sort[0].selector;\r\n                               " +
"             if (loadOptions.sort[0].desc)\r\n                                    " +
"            args.orderby += \" desc\";\r\n                                        }\r" +
"\n\r\n                                        $.ajax({\r\n                           " +
"                 url: \"../System/GetCOW_PermissionEmployeeInquiry?menuCode=\" + t" +
"reeSelectedRow.selectedRowsData[0].MenuCode,\r\n                                  " +
"          dataType: \"json\",\r\n                                            data: a" +
"rgs,\r\n                                            success: function (result) {\r\n" +
"                                                deferred.resolve(result.data);\r\n" +
"                                            },\r\n                                " +
"            error: function (e) {\r\n                                             " +
"   console.log(\"오류발생\");\r\n                                                console" +
".log(e);\r\n                                                deferred.reject(\"Data " +
"Loading Error\");\r\n                                            },\r\n              " +
"                              timeout: 10000\r\n                                  " +
"      });\r\n                                        return deferred.promise();\r\n " +
"                                   }\r\n                                });\r\n     " +
"                           $(\"#gridContainer03\").dxDataGrid({\r\n                 " +
"                   dataSource: {\r\n                                        store:" +
" orders\r\n                                    }\r\n                                " +
"}).dxDataGrid(\"instance\").refresh();\r\n                            }\r\n           " +
"             }\r\n                    }\r\n                } catch (e) {\r\n          " +
"          console.log(e);\r\n                }\r\n            });\r\n            //작업자" +
" 권한없음 버튼 클릭\r\n            $(\'#btnNoAuthEmployee\').click(function () {\r\n\r\n        " +
"        try {\r\n                    if (treeSelectedRow) {\r\n                     " +
"   var pids = $(\'#gridContainer03\').dxDataGrid(\'instance\').getSelectedRowsData()" +
";\r\n                        if (pids.length > 0) {\r\n                            i" +
"f (SetCOW_PermissionEmployeeNoAuthSave(treeSelectedRow.selectedRowsData[0].MenuC" +
"ode, pids)) {\r\n                                var orders = new DevExpress.data." +
"CustomStore({\r\n                                    load: function (loadOptions) " +
"{\r\n                                        var deferred = $.Deferred(),\r\n       " +
"                                     args = {};\r\n\r\n                             " +
"           if (loadOptions.sort) {\r\n                                            " +
"args.orderby = loadOptions.sort[0].selector;\r\n                                  " +
"          if (loadOptions.sort[0].desc)\r\n                                       " +
"         args.orderby += \" desc\";\r\n                                        }\r\n\r\n" +
"                                        $.ajax({\r\n                              " +
"              url: \"../System/GetCOW_PermissionEmployeeInquiry?menuCode=\" + tree" +
"SelectedRow.selectedRowsData[0].MenuCode,\r\n                                     " +
"       dataType: \"json\",\r\n                                            data: args" +
",\r\n                                            success: function (result) {\r\n   " +
"                                             deferred.resolve(result.data);\r\n   " +
"                                         },\r\n                                   " +
"         error: function (e) {\r\n                                                " +
"console.log(\"오류발생\");\r\n                                                console.lo" +
"g(e);\r\n                                                deferred.reject(\"Data Loa" +
"ding Error\");\r\n                                            },\r\n                 " +
"                           timeout: 10000\r\n                                     " +
"   });\r\n                                        return deferred.promise();\r\n    " +
"                                }\r\n                                });\r\n        " +
"                        $(\"#gridContainer03\").dxDataGrid({\r\n                    " +
"                dataSource: {\r\n                                        store: or" +
"ders\r\n                                    }\r\n                                })." +
"dxDataGrid(\"instance\").refresh();\r\n                            }\r\n              " +
"          }\r\n                    }\r\n                } catch (e) {\r\n             " +
"       console.log(e);\r\n                }\r\n            });\r\n\r\n            //작업자추" +
"가 버튼 클릭\r\n            $(\'#btnAddEmployee\').click(function () {\r\n\r\n               " +
" if (treeSelectedRow) {\r\n                    var vv = $(\'#gridContainer03\').dxDa" +
"taGrid(\'instance\').getDataSource();\r\n                    Popup_PermissionEmploye" +
"eAdd(treeSelectedRow.selectedRowsData[0].MenuCode, vv.items());\r\n               " +
" }\r\n            });\r\n\r\n            //작업자삭제 버튼 클릭\r\n            $(\'#btnRemoveEmplo" +
"yee\').click(function () {\r\n\r\n                try {\r\n                    if (tree" +
"SelectedRow) {\r\n                        var pids = $(\'#gridContainer03\').dxDataG" +
"rid(\'instance\').getSelectedRowsData();\r\n                        if (pids.length " +
"> 0) {\r\n                            if (SetCOW_PermissionEmployeeRemoveSave(tree" +
"SelectedRow.selectedRowsData[0].MenuCode, pids)) {\r\n                            " +
"    var orders = new DevExpress.data.CustomStore({\r\n                            " +
"        load: function (loadOptions) {\r\n                                        " +
"var deferred = $.Deferred(),\r\n                                            args =" +
" {};\r\n\r\n                                        if (loadOptions.sort) {\r\n       " +
"                                     args.orderby = loadOptions.sort[0].selector" +
";\r\n                                            if (loadOptions.sort[0].desc)\r\n  " +
"                                              args.orderby += \" desc\";\r\n        " +
"                                }\r\n\r\n                                        $.a" +
"jax({\r\n                                            url: \"../System/GetCOW_Permis" +
"sionEmployeeInquiry?menuCode=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n" +
"                                            dataType: \"json\",\r\n                 " +
"                           data: args,\r\n                                        " +
"    success: function (result) {\r\n                                              " +
"  deferred.resolve(result.data);\r\n                                            }," +
"\r\n                                            error: function (e) {\r\n           " +
"                                     console.log(\"오류발생\");\r\n                     " +
"                           console.log(e);\r\n                                    " +
"            deferred.reject(\"Data Loading Error\");\r\n                            " +
"                },\r\n                                            timeout: 10000\r\n" +
"                                        });\r\n                                   " +
"     return deferred.promise();\r\n                                    }\r\n        " +
"                        });\r\n                                $(\"#gridContainer03" +
"\").dxDataGrid({\r\n                                    dataSource: {\r\n            " +
"                            store: orders\r\n                                    }" +
"\r\n                                }).dxDataGrid(\"instance\").refresh();\r\n        " +
"                    }\r\n                        }\r\n                    }\r\n       " +
"         } catch (e) {\r\n                    console.log(e);\r\n                }\r\n" +
"            });\r\n\r\n            //중복?\r\n            //$(\'#btnReadRoleAdd\').click(f" +
"unction () {\r\n            //});\r\n\r\n            //추가 권한 추가\r\n            function " +
"SetCOW_PermissionRoleCreateSave(pmenuCode, pids) {\r\n                try\r\n       " +
"         {\r\n                    var dat = \"\";\r\n                    for (var i = " +
"0; i < pids.length; i++) {\r\n                        dat += pids[i].RoleId + \',\';" +
"\r\n                    }\r\n\r\n                    $.post(\'../System/SetCOW_Permissi" +
"onRoleCreateSave\', { menuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n     " +
"               }).fail(function (jqXHR, textStatus, errorThrown) {\r\n            " +
"            alert(\'Error getting products!\');\r\n                    });\r\n        " +
"            return true;\r\n                } catch (e) {\r\n                    ret" +
"urn false;\r\n                }\r\n            }\r\n\r\n            //읽기 권한 추가\r\n        " +
"    function SetCOW_PermissionRoleReadSave(pmenuCode, pids) {\r\n                t" +
"ry{\r\n                    var dat = \"\";\r\n                    for (var i = 0; i < " +
"pids.length; i++) {\r\n                        dat += pids[i].RoleId + \',\';\r\n     " +
"               }\r\n                    $.post(\'../System/SetCOW_PermissionRoleRea" +
"dSave\', { menuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n                " +
"    }).fail(function (jqXHR, textStatus, errorThrown) {\r\n                       " +
" alert(\'Error getting products!\');\r\n                    });\r\n                   " +
" return true;\r\n                } catch (e) {\r\n                    return false;\r" +
"\n                }\r\n            }\r\n\r\n            //수정 권한 추가\r\n            functio" +
"n SetCOW_PermissionRoleUpdateSave(pmenuCode, pids) {\r\n                try {\r\n   " +
"                 var dat = \"\";\r\n                    for (var i = 0; i < pids.len" +
"gth; i++) {\r\n                        dat += pids[i].RoleId + \',\';\r\n             " +
"       }\r\n                    $.post(\'../System/SetCOW_PermissionRoleUpdateSave\'" +
", { menuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n                    })" +
".fail(function (jqXHR, textStatus, errorThrown) {\r\n                        alert" +
"(\'Error getting products!\');\r\n                    });\r\n                    retur" +
"n true;\r\n                } catch (e) {\r\n                    return false;\r\n     " +
"           }\r\n            }\r\n\r\n            //삭제 권한 추가\r\n            function SetC" +
"OW_PermissionRoleDeleteSave(pmenuCode, pids) {\r\n                try {\r\n         " +
"           var dat = \"\";\r\n                    for (var i = 0; i < pids.length; i" +
"++) {\r\n                        dat += pids[i].RoleId + \',\';\r\n                   " +
" }\r\n                    $.post(\'../System/SetCOW_PermissionRoleDeleteSave\', { me" +
"nuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n                    }).fail(" +
"function (jqXHR, textStatus, errorThrown) {\r\n                        alert(\'Erro" +
"r getting products!\');\r\n                    });\r\n                    return true" +
";\r\n                } catch (e) {\r\n                    return false;\r\n           " +
"     }\r\n            }\r\n\r\n            //권한없음 처리\r\n            function SetCOW_Perm" +
"issionRoleNoAuthSave(pmenuCode, pids) {\r\n                try {\r\n                " +
"    var dat = \"\";\r\n                    for (var i = 0; i < pids.length; i++) {\r\n" +
"                        dat += pids[i].RoleId + \',\';\r\n                    }\r\n   " +
"                 $.post(\'../System/SetCOW_PermissionRoleNoAuthSave\', { menuCode:" +
" pmenuCode, ids: dat }, function (data) {\r\n\r\n                    }).fail(functio" +
"n (jqXHR, textStatus, errorThrown) {\r\n                        alert(\'Error getti" +
"ng products!\');\r\n                    });\r\n                    return true;\r\n    " +
"            } catch (e) {\r\n                    return false;\r\n                }\r" +
"\n            }\r\n\r\n            //권한 추가?\r\n            function SetCOW_PermissionRo" +
"leAddSave(pmenuCode, pids) {\r\n                try {\r\n                    var dat" +
" = \"\";\r\n                    $.post(\'../System/SetCOW_PermissionRoleAddSave\', { m" +
"enuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n                    }).fail" +
"(function (jqXHR, textStatus, errorThrown) {\r\n                        alert(\'Err" +
"or getting products!\');\r\n                    });\r\n                    return tru" +
"e;\r\n                } catch (e) {\r\n                    return false;\r\n          " +
"      }\r\n            }\r\n\r\n            //권한삭제 처리\r\n            function SetCOW_Per" +
"missionRoleRemoveSave(pmenuCode, pids) {\r\n                try {\r\n               " +
"     var dat = \"\";\r\n                    for (var i = 0; i < pids.length; i++) {\r" +
"\n                        dat += pids[i].RoleId + \',\';\r\n                    }\r\n  " +
"                  $.post(\'../System/SetCOW_PermissionRoleRemoveSave\', { menuCode" +
": pmenuCode, ids: dat }, function (data) {\r\n\r\n                    }).fail(functi" +
"on (jqXHR, textStatus, errorThrown) {\r\n                        alert(\'Error gett" +
"ing products!\');\r\n                    });\r\n                    return true;\r\n   " +
"             } catch (e) {\r\n                    return false;\r\n                }" +
"\r\n            }\r\n\r\n            //선택된 작업자 추가 권한 부여\r\n            function SetCOW_P" +
"ermissionEmployeeCreateSave(pmenuCode, pids) {\r\n                try {\r\n         " +
"           var dat = \"\";\r\n                    for (var i = 0; i < pids.length; i" +
"++) {\r\n                        dat += pids[i].EmployeeId + \',\';\r\n               " +
"     }\r\n                    $.post(\'../System/SetCOW_PermissionEmployeeCreateSav" +
"e\', { menuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n                    " +
"}).fail(function (jqXHR, textStatus, errorThrown) {\r\n                        ale" +
"rt(\'Error getting products!\');\r\n                    });\r\n                    ret" +
"urn true;\r\n                } catch (e) {\r\n                    return false;\r\n   " +
"             }\r\n            }\r\n\r\n            //선택된 작업자 읽기 권한 부여\r\n            fun" +
"ction SetCOW_PermissionEmployeeReadSave(pmenuCode, pids) {\r\n                try " +
"{\r\n                    var dat = \"\";\r\n                    for (var i = 0; i < pi" +
"ds.length; i++) {\r\n                        dat += pids[i].EmployeeId + \',\';\r\n   " +
"                 }\r\n                    $.post(\'../System/SetCOW_PermissionEmplo" +
"yeeReadSave\', { menuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n          " +
"          }).fail(function (jqXHR, textStatus, errorThrown) {\r\n                 " +
"       alert(\'Error getting products!\');\r\n                    });\r\n             " +
"       return true;\r\n                } catch (e) {\r\n                    return f" +
"alse;\r\n                }\r\n            }\r\n\r\n            //선택된 작업자 수정 권한 부여\r\n     " +
"       function SetCOW_PermissionEmployeeUpdateSave(pmenuCode, pids) {\r\n        " +
"        try {\r\n                    var dat = \"\";\r\n                    for (var i" +
" = 0; i < pids.length; i++) {\r\n                        dat += pids[i].EmployeeId" +
" + \',\';\r\n                    }\r\n                    $.post(\'../System/SetCOW_Per" +
"missionEmployeeUpdateSave\', { menuCode: pmenuCode, ids: dat }, function (data) {" +
"\r\n\r\n                    }).fail(function (jqXHR, textStatus, errorThrown) {\r\n   " +
"                     alert(\'Error getting products!\');\r\n                    });\r" +
"\n                    return true;\r\n                } catch (e) {\r\n              " +
"      return false;\r\n                }\r\n            }\r\n\r\n            //선택된 작업자 삭" +
"제\r\n            function SetCOW_PermissionEmployeeDeleteSave(pmenuCode, pids) {\r\n" +
"                try {\r\n                    var dat = \"\";\r\n                    fo" +
"r (var i = 0; i < pids.length; i++) {\r\n                        dat += pids[i].Em" +
"ployeeId + \',\';\r\n                    }\r\n                    $.post(\'../System/Se" +
"tCOW_PermissionEmployeeDeleteSave\', { menuCode: pmenuCode, ids: dat }, function " +
"(data) {\r\n\r\n                    }).fail(function (jqXHR, textStatus, errorThrown" +
") {\r\n                        alert(\'Error getting products!\');\r\n                " +
"    });\r\n                    return true;\r\n                } catch (e) {\r\n      " +
"              return false;\r\n                }\r\n            }\r\n\r\n            //선" +
"택된 작업자 권한없음 처리\r\n            function SetCOW_PermissionEmployeeNoAuthSave(pmenuCo" +
"de, pids) {\r\n                try {\r\n                    var dat = \"\";\r\n         " +
"           for (var i = 0; i < pids.length; i++) {\r\n                        dat " +
"+= pids[i].EmployeeId + \',\';\r\n                    }\r\n                    $.post(" +
"\'../System/SetCOW_PermissionEmployeeNoAuthSave\', { menuCode: pmenuCode, ids: dat" +
" }, function (data) {\r\n\r\n                    }).fail(function (jqXHR, textStatus" +
", errorThrown) {\r\n                        alert(\'Error getting products!\');\r\n   " +
"                 });\r\n                    return true;\r\n                } catch " +
"(e) {\r\n                    return false;\r\n                }\r\n            }\r\n\r\n  " +
"          //작업자 추가??\r\n            //function SetCOW_PermissionEmployeeAddSave(pm" +
"enuCode, pids) {\r\n            //    try {\r\n            //        var dat = \"\";\r\n" +
"            //        $.post(\'../System/SetCOW_PermissionEmployeeAddSave\', { men" +
"uCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n            //        }).fail" +
"(function (jqXHR, textStatus, errorThrown) {\r\n            //            alert(\'E" +
"rror getting products!\');\r\n            //        });\r\n            //        retu" +
"rn true;\r\n            //    } catch (e) {\r\n            //        return false;\r\n" +
"            //    }\r\n            //}\r\n\r\n            //선택된 작업자 삭제\r\n            fu" +
"nction SetCOW_PermissionEmployeeRemoveSave(pmenuCode, pids) {\r\n                t" +
"ry {\r\n                    var dat = \"\";\r\n                    for (var i = 0; i <" +
" pids.length; i++) {\r\n                        dat += pids[i].EmployeeId + \',\';\r\n" +
"                    }\r\n                    $.post(\'../System/SetCOW_PermissionEm" +
"ployeeRemoveSave\', { menuCode: pmenuCode, ids: dat }, function (data) {\r\n\r\n     " +
"               }).fail(function (jqXHR, textStatus, errorThrown) {\r\n            " +
"            alert(\'Error getting products!\');\r\n                    });\r\n        " +
"            return true;\r\n                } catch (e) {\r\n                    ret" +
"urn false;\r\n                }\r\n            }\r\n\r\n            //역할추가 팝업 Load\r\n    " +
"        function Popup_PermissionRoleAdd(pmenuCode, pids) {\r\n                var" +
" dat = \"\";\r\n                for (var i = 0; i < pids.length; i++) {\r\n           " +
"         dat += pids[i].RoleId + \',\';\r\n                }\r\n                consol" +
"e.log(pids);\r\n                $.post(\'../System/Popup_PermissionRoleAdd\', { menu" +
"Code: pmenuCode, ids: dat }, function (data) {\r\n                    $(\'#Modals\')" +
".html(data);\r\n\r\n                }).fail(function (jqXHR, textStatus, errorThrown" +
") {\r\n                    alert(\'Error getting products!\');\r\n                });\r" +
"\n                return;\r\n            }\r\n\r\n\r\n            //역할추가 팝업창 사라지면 재조회\r\n  " +
"          $(\'#Modals\').on(\'hidden.bs.modal\', function () {\r\n                if (" +
"treeSelectedRow) {\r\n                    var orders = new DevExpress.data.CustomS" +
"tore({\r\n                        load: function (loadOptions) {\r\n                " +
"            var deferred = $.Deferred(),\r\n                                args =" +
" {};\r\n\r\n                            if (loadOptions.sort) {\r\n                   " +
"             args.orderby = loadOptions.sort[0].selector;\r\n                     " +
"           if (loadOptions.sort[0].desc)\r\n                                    ar" +
"gs.orderby += \" desc\";\r\n                            }\r\n\r\n                       " +
"     $.ajax({\r\n                                url: \"../System/GetCOW_Permission" +
"RoleInquiry?menuCode=\" + treeSelectedRow.selectedRowsData[0].MenuCode,\r\n        " +
"                        dataType: \"json\",\r\n                                data:" +
" args,\r\n                                success: function (result) {\r\n          " +
"                          deferred.resolve(result.data);\r\n                      " +
"          },\r\n                                error: function (e) {\r\n           " +
"                         console.log(\"오류발생\");\r\n                                 " +
"   console.log(e);\r\n                                    deferred.reject(\"Data Lo" +
"ading Error\");\r\n                                },\r\n                            " +
"    timeout: 10000\r\n                            });\r\n                           " +
" return deferred.promise();\r\n                        }\r\n                    });\r" +
"\n                    $(\"#gridContainer02\").dxDataGrid({\r\n                       " +
" dataSource: {\r\n                            store: orders\r\n                     " +
"   }\r\n                    }).dxDataGrid(\"instance\").refresh();\r\n                " +
"}\r\n            })\r\n\r\n\r\n            //작업자추가 팝업창 Load\r\n            function Popup_" +
"PermissionEmployeeAdd(pmenuCode, pids) {\r\n                var dat = \"\";\r\n       " +
"         for (var i = 0; i < pids.length; i++) {\r\n                    dat += pid" +
"s[i].EmployeeId + \',\';\r\n                }\r\n                $.post(\'../System/Pop" +
"up_PermissionEmployeeAdd\', { menuCode: pmenuCode, ids: dat }, function (data) {\r" +
"\n                    $(\'#ModalsEmployee\').html(data);\r\n\r\n                }).fail" +
"(function (jqXHR, textStatus, errorThrown) {\r\n                    alert(\'Error g" +
"etting products!\');\r\n                });\r\n                return;\r\n            }" +
"\r\n\r\n\r\n            //작업자추가 팝업창이 사라지면 재조회\r\n            $(\'#ModalsEmployee\').on(\'hi" +
"dden.bs.modal\', function () {\r\n                if (treeSelectedRow) {\r\n         " +
"           var orders = new DevExpress.data.CustomStore({\r\n                     " +
"   load: function (loadOptions) {\r\n                            var deferred = $." +
"Deferred(),\r\n                                args = {};\r\n\r\n                     " +
"       if (loadOptions.sort) {\r\n                                args.orderby = l" +
"oadOptions.sort[0].selector;\r\n                                if (loadOptions.so" +
"rt[0].desc)\r\n                                    args.orderby += \" desc\";\r\n     " +
"                       }\r\n\r\n                            $.ajax({\r\n              " +
"                  url: \"../System/GetCOW_PermissionEmployeeInquiry?menuCode=\" + " +
"treeSelectedRow.selectedRowsData[0].MenuCode,\r\n                                d" +
"ataType: \"json\",\r\n                                data: args,\r\n                 " +
"               success: function (result) {\r\n                                   " +
" deferred.resolve(result.data);\r\n                                },\r\n           " +
"                     error: function (e) {\r\n                                    " +
"console.log(\"오류발생\");\r\n                                    console.log(e);\r\n     " +
"                               deferred.reject(\"Data Loading Error\");\r\n         " +
"                       },\r\n                                timeout: 10000\r\n     " +
"                       });\r\n                            return deferred.promise(" +
");\r\n                        }\r\n                    });\r\n                    $(\"#" +
"gridContainer03\").dxDataGrid({\r\n                        dataSource: {\r\n         " +
"                   store: orders\r\n                        }\r\n                   " +
" }).dxDataGrid(\"instance\").refresh();\r\n                }\r\n            });\r\n\r\n   " +
"     });\r\n    </script>\r\n");

});

WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
